import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function Splash() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex flex-col justify-center items-center bg-primary-100 text-4xl min-h-screen font-bold text-primary-600">
          <div className=" w-fit">
            <div>DELTA Profile Viewer Website</div>
            <div className=" bg-secondary-600 p-1 rounded-full mt-4"></div>
          </div>
        </div>
      </main>
    </>
  );
}
